---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: Pod
metadata:
  name: beam-app
  labels:
    app: web
spec:
  containers:
    - name: beam
      image: t40mas/beam
      imagePullPolicy: Never
      resources:
        limits:
          memory: 512Mi
          cpu: '1'
      ports:
        - containerPort: 3000
    - name: postgres
      image: postgres:latest
      imagePullPolicy: 'IfNotPresent'
      envFrom:
        - configMapRef:
            name: postgres-config
      ports:
        - containerPort: 5432
      resources:
        limits:
          memory: 512Mi
          cpu: '1'
